# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_boardInterface(object):
    def setupUi(self, boardInterface):
        boardInterface.setObjectName("boardInterface")
        boardInterface.resize(379, 812)
        boardInterface.setStyleSheet("#boardInterface{background-color: #CDE7F2}")
        self.Home = QtWidgets.QLabel(boardInterface)
        self.Home.setGeometry(QtCore.QRect(40, 50, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.Home.setFont(font)
        self.Home.setStyleSheet("color: #1049BB\n"
"")
        self.Home.setObjectName("Home")
        self.icon = QtWidgets.QLabel(boardInterface)
        self.icon.setGeometry(QtCore.QRect(290, 50, 41, 41))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap(":/mapping/img/icon.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.dashboard = QtWidgets.QWidget(boardInterface)
        self.dashboard.setGeometry(QtCore.QRect(180, 100, 21, 20))
        self.dashboard.setObjectName("dashboard")
        self.line = QtWidgets.QFrame(boardInterface)
        self.line.setGeometry(QtCore.QRect(0, 710, 381, 20))
        self.line.setMinimumSize(QtCore.QSize(0, 20))
        self.line.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.home_icon = QtWidgets.QLabel(boardInterface)
        self.home_icon.setGeometry(QtCore.QRect(5, 725, 101, 51))
        self.home_icon.setText("")
        self.home_icon.setPixmap(QtGui.QPixmap(":/mapping/img/home.png"))
        self.home_icon.setScaledContents(True)
        self.home_icon.setObjectName("home_icon")
        self.contact_icon = QtWidgets.QLabel(boardInterface)
        self.contact_icon.setGeometry(QtCore.QRect(110, 735, 71, 41))
        self.contact_icon.setText("")
        self.contact_icon.setPixmap(QtGui.QPixmap(":/mapping/img/contact.png"))
        self.contact_icon.setObjectName("contact_icon")
        self.analysis_icon = QtWidgets.QLabel(boardInterface)
        self.analysis_icon.setGeometry(QtCore.QRect(190, 732, 61, 51))
        self.analysis_icon.setText("")
        self.analysis_icon.setPixmap(QtGui.QPixmap(":/mapping/img/ analysis.png"))
        self.analysis_icon.setObjectName("analysis_icon")
        self.setting_icon = QtWidgets.QLabel(boardInterface)
        self.setting_icon.setGeometry(QtCore.QRect(250, 730, 91, 41))
        self.setting_icon.setText("")
        self.setting_icon.setPixmap(QtGui.QPixmap(":/mapping/img/setting.png"))
        self.setting_icon.setObjectName("setting_icon")
        self.line_2 = QtWidgets.QFrame(boardInterface)
        self.line_2.setGeometry(QtCore.QRect(0, 780, 381, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.quick_control = QtWidgets.QLabel(boardInterface)
        self.quick_control.setGeometry(QtCore.QRect(50, 600, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.quick_control.setFont(font)
        self.quick_control.setStyleSheet("color: #1049BB")
        self.quick_control.setObjectName("quick_control")
        self.plus = QtWidgets.QPushButton(boardInterface)
        self.plus.setGeometry(QtCore.QRect(40, 640, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.plus.setFont(font)
        self.plus.setStyleSheet("color: rgb(25, 224, 73)")
        self.plus.setObjectName("plus")
        self.reduce = QtWidgets.QPushButton(boardInterface)
        self.reduce.setGeometry(QtCore.QRect(210, 640, 131, 32))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.reduce.setFont(font)
        self.reduce.setStyleSheet("color: rgb(255, 38, 0)")
        self.reduce.setObjectName("reduce")
        self.live_readings = QtWidgets.QLabel(boardInterface)
        self.live_readings.setGeometry(QtCore.QRect(120, 160, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.live_readings.setFont(font)
        self.live_readings.setStyleSheet("color: #1049BB")
        self.live_readings.setObjectName("live_readings")
        self.Home.raise_()
        self.icon.raise_()
        self.line.raise_()
        self.home_icon.raise_()
        self.contact_icon.raise_()
        self.analysis_icon.raise_()
        self.setting_icon.raise_()
        self.line_2.raise_()
        self.quick_control.raise_()
        self.plus.raise_()
        self.reduce.raise_()
        self.live_readings.raise_()
        self.dashboard.raise_()

        self.retranslateUi(boardInterface)
        QtCore.QMetaObject.connectSlotsByName(boardInterface)

    def retranslateUi(self, boardInterface):
        _translate = QtCore.QCoreApplication.translate
        boardInterface.setWindowTitle(_translate("boardInterface", "Form"))
        self.Home.setText(_translate("boardInterface", "Home"))
        self.quick_control.setText(_translate("boardInterface", "Quick Controls"))
        self.plus.setText(_translate("boardInterface", "+ 0.5 L / min"))
        self.reduce.setText(_translate("boardInterface", "- 0.5 L / min"))
        self.live_readings.setText(_translate("boardInterface", "Live Readings"))

import img_rc
